// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrBx0s-xHf0hBCJ2b_DEkfFl3emmF6B10',
    appId: '1:636357630680:android:f177b0a09d8a0f680755ad',
    messagingSenderId: '636357630680',
    projectId: 'dumbkey-1ecf8',
    storageBucket: 'dumbkey-1ecf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJcKBLJ56Kk-pfzIFq1glmhPaEmn45UC8',
    appId: '1:636357630680:ios:5ecdcbcd9bad37aa0755ad',
    messagingSenderId: '636357630680',
    projectId: 'dumbkey-1ecf8',
    storageBucket: 'dumbkey-1ecf8.appspot.com',
    iosClientId: '636357630680-paeu2q3a44s5p1v2n4roi039kfretec1.apps.googleusercontent.com',
    iosBundleId: 'app.dumbapps.dumbkey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJcKBLJ56Kk-pfzIFq1glmhPaEmn45UC8',
    appId: '1:636357630680:ios:d504f9a8d501716d0755ad',
    messagingSenderId: '636357630680',
    projectId: 'dumbkey-1ecf8',
    storageBucket: 'dumbkey-1ecf8.appspot.com',
    iosClientId: '636357630680-1esvaq50fbg961qj8m64otil3gm34ral.apps.googleusercontent.com',
    iosBundleId: 'app.dumbapps.dumbkey.RunnerTests',
  );
}
