name: 'build-app'

on: # 2
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # Build on tags that start with 'v'


jobs:
    build_android:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: setup env file
          uses: SpicyPizza/create-envfile@v2.0
          with:
            envkey_FIREBASE_APIKEY : $ {{ secrets.FIREBASE_APIKEY }}
            envkey_FIREBASE_PROJECTID : ${{ secrets.FIREBASE_PROJECTID }}

        - uses: subosito/flutter-action@v2
          with:
            flutter-version: "3.10.6"
            channel: 'stable'

        - name: Get dependencies
          run: flutter pub get

        - name: analyze code
          run: flutter analyze .

        # Runs a set of commands using the runners shell
        - name: Start release build
          run: flutter build apk

        - uses: actions/upload-artifact@v3
          with:
            # Name of the command/step.
            name: build apk
            # Path to the release apk.
            path: build/app/outputs/apk/release/app-release.apk